language: php
php:
    - nightly

install:
    - composer install --no-interaction
    - composer update --no-interaction

script: phpunit --bootstrap tests/autoload.php --no-globals-backup --stderr -v --debug tests